#!/usr/bin/env bash
# Extracts dominant colors from the current wallpaper and writes
# ~/.config/hypr/wallust/border-colors.conf, then reloads Hyprland.

# Prefer live awww query, fall back to .wallpaper_current
WALLPAPER="${1:-$(awww query 2>/dev/null | grep -oP 'image: \K[^\s]+' | head -1)}"
WALLPAPER="${WALLPAPER:-$HOME/.config/hypr/wallpaper_effects/.wallpaper_current}"
OUT="$HOME/.config/hypr/wallust/border-colors.conf"

[ -f "$WALLPAPER" ] || exit 0

python3 - "$WALLPAPER" "$OUT" << 'EOF'
import sys
from PIL import Image

wallpaper, out = sys.argv[1], sys.argv[2]

img = Image.open(wallpaper).convert('RGB')
small = img.resize((200, 200))
quantized = small.quantize(colors=8, method=Image.Quantize.FASTOCTREE)
palette = quantized.getpalette()[:8 * 3]
colors = [(palette[i*3], palette[i*3+1], palette[i*3+2]) for i in range(8)]
# Sort light → dark by perceived brightness
colors.sort(key=lambda c: 0.299*c[0] + 0.587*c[1] + 0.114*c[2], reverse=True)

def hex8(r, g, b, a=255):
    return f'{r:02x}{g:02x}{b:02x}{a:02x}'

active1   = colors[0]   # brightest dominant
active2   = colors[1]   # second brightest
inactive  = colors[-2]  # near-darkest
shadow_a  = colors[2]   # mid-bright
shadow_i  = colors[-1]  # darkest

with open(out, 'w') as f:
    f.write('# Auto-generated by UpdateBorderColors.sh — do not edit\n')
    f.write(f'$border_active1  = rgba({hex8(*active1)})\n')
    f.write(f'$border_active2  = rgba({hex8(*active2)})\n')
    f.write(f'$border_inactive = rgba({hex8(*inactive)})\n')
    f.write(f'$shadow_active   = rgba({hex8(*shadow_a, 238)})\n')
    f.write(f'$shadow_inactive = rgba({hex8(*shadow_i, 153)})\n')

print(f'border-colors: active={hex8(*active1)}->{hex8(*active2)} inactive={hex8(*inactive)}')
EOF

hyprctl reload >/dev/null 2>&1 &
